spring:
  application:
    name: sched-alert-bot
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/sched_alert_bot}
mongock:
  migration-scan-package: com.github.viktor235.schedalertbot.migration
  enabled: true
telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_NAME}
logging:
  level:
    com.github.viktor235.schedalertbot: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "health,info,scheduledtasks,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

site:
  stopgame:
    scheduler:
      cron: "0 1/10 * * * *"
    scraper:
      url: https://stopgame.ru/live_schedule
      selector:
        event: "//div[@data-key and .//div[contains(@class, '_stream_')]]"
        id: "./@data-key"
        name: ".//*[contains(@class, '_stream-title_')]"
        date: ".//*[contains(@class, '_stream-info_')]/*[1]//*[contains(@class, '_stream-info__value_')]"
        time: ".//*[contains(@class, '_stream-info_')]/*[2]//*[contains(@class, '_stream-info__value_')]"
        description: ".//*[contains(@class, '_stream-description_')]"
        participants: ".//*[contains(@class, '_user-info__name_')]"
